name: Xcode - Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and test UberRides and UberCore
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./source

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test UberRides
        run: |
          xcodebuild test -destination "platform=iOS Simulator,name=iPhone 15 Pro" -scheme "UberRides" -project "UberRides.xcodeproj"
      - name: Test UberCore
        run: |
          xcodebuild test -destination "platform=iOS Simulator,name=iPhone 15 Pro" -scheme "UberCore" -project "UberRides.xcodeproj"
